const byId = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;

export const elements = {
  activePhoneRequest: byId<HTMLDivElement>("active-phone-request"),
  phonePurpose: byId<HTMLHeadingElement>("phone-purpose"),
  phoneRequest: byId<HTMLPreElement>("phone-request"),
  tokenUsagePopover: byId<HTMLDivElement>("token-usage-popover"),
  tokenUsageTrigger: byId<HTMLButtonElement>("token-usage-trigger"),
  tokenUsageTriggerTotal: byId<HTMLSpanElement>("token-usage-trigger-total"),
  tokenUsageDetails: byId<HTMLDivElement>("token-usage-details"),
  tokenUsageState: byId<HTMLSpanElement>("token-usage-state"),
  tokenUsageInput: byId<HTMLElement>("token-usage-input"),
  tokenUsageOutput: byId<HTMLElement>("token-usage-output"),
  tokenUsageCachedInput: byId<HTMLElement>("token-usage-cached-input"),
  tokenUsageReasoningOutput: byId<HTMLElement>("token-usage-reasoning-output"),
  tokenUsageTotal: byId<HTMLElement>("token-usage-total"),
  tokenUsageContextWindow: byId<HTMLSpanElement>("token-usage-context-window"),
  tokenEstimatedCost: byId<HTMLElement>("token-estimated-cost"),
  tokenPricingBreakdown: byId<HTMLDivElement>("token-pricing-breakdown"),
  tokenUsageMeta: byId<HTMLDivElement>("token-usage-meta"),
  sessionBadge: byId<HTMLSpanElement>("session-badge"),
  logCount: byId<HTMLSpanElement>("log-count"),
  logCountBadge: byId<HTMLSpanElement>("log-count-badge"),
  clearLogs: byId<HTMLButtonElement>("clear-logs"),
  toolCount: byId<HTMLSpanElement>("tool-count"),
  toolCountBadge: byId<HTMLSpanElement>("tool-count-badge"),
  clearToolCalls: byId<HTMLButtonElement>("clear-tool-calls"),
  expandToolCalls: byId<HTMLInputElement>("expand-tool-calls"),
  toolList: byId<HTMLDivElement>("tool-list"),
  toolScrollContainer: byId<HTMLDivElement>("tool-scroll-container"),
  agentPlan: byId<HTMLElement>("agent-plan"),
  agentPlanProgress: byId<HTMLSpanElement>("agent-plan-progress"),
  agentPlanExplanation: byId<HTMLParagraphElement>("agent-plan-explanation"),
  agentPlanSteps: byId<HTMLOListElement>("agent-plan-steps"),
  toolImageDialog: byId<HTMLDialogElement>("tool-image-dialog"),
  toolImageDialogGallery: byId<HTMLDivElement>("tool-image-dialog-gallery"),
  toolImageDialogImage: byId<HTMLImageElement>("tool-image-dialog-image"),
  toolImageDialogLabel: byId<HTMLSpanElement>("tool-image-dialog-label"),
  closeToolImageDialog: byId<HTMLButtonElement>("close-tool-image-dialog"),
  discoverPhones: byId<HTMLButtonElement>("discover-phones"),
  discoveryStatus: byId<HTMLSpanElement>("discovery-status"),
  discoveredPhones: byId<HTMLDivElement>("discovered-phones"),
  toolsTab: byId<HTMLElement>("tab-tools"),
  logList: byId<HTMLDivElement>("log-list"),
  logScrollContainer: byId<HTMLDivElement>("log-scroll-container"),
  toast: byId<HTMLDivElement>("toast"),
  toastIcon: document.getElementById("toast-icon") as HTMLDivElement | null,
  toastMessage: document.getElementById("toast-message") as HTMLSpanElement | null,
  toastClose: document.getElementById("toast-close") as HTMLButtonElement | null,
  connectionStatusPill: document.getElementById("connection-status-pill") as HTMLSpanElement | null
};

export function setText(element: HTMLElement, value: string): void {
  element.textContent = value;
}
